### ISSUE TITLE
Click "View Bots" button raise "RuntimeError: no running event loop"

### ISSUE THREAD

**Issue by CrazyZfp** [freqtrade/ftui#10]
RuntimeError: no running event loop

NOTE: 1 of 2 errors shown. Run with textual run --dev to see all errors.
sys:1: RuntimeWarning: coroutine 'MessagePump._process_messages' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by froggleston** [comment]
Fixed in https://github.com/freqtrade/ftui/commit/6ad4cf52ef7245a9f97cf4d3be00ef5110175a06
