### ISSUE TITLE
install freqtrade-ftui failed

### ISSUE THREAD

**Issue by XinuxC** [freqtrade/ftui#3]
when I run command: pip3 install freqtrade-ftui
the following error:
ERROR: Could not find a version that satisfies the requirement freqtrade-ftui (from versions: none)
ERROR: No matching distribution found for freqtrade-ftui

how?

**Comment by froggleston** [comment]
Yes, there is no pip installable package. Please use the instructions in the readme.

**Comment by froggleston** [comment]
I've updated the instructions until I've created and released a full package.

**Comment by froggleston** [comment]
Thanks to @xmatthias (https://pypi.org/project/ftui/) FTUI can now be installed via pip: `pip install ftui`

**Comment by XinuxC** [comment]
> Thanks to @xmatthias (https://pypi.org/project/ftui/) FTUI can now be installed via pip: `pip install ftui`

appreciate it
